const std       = @import("std");
const os        = @import("os.zig");
const log       = @import("log.zig");
const XmlParser = @import("xml_parser.zig");
const assert    = std.debug.assert;
const Writer    = std.Io.Writer;

const IN_PATHS = [_][*:0]const u8{
  "thirdparty/wayland.xml",
  "thirdparty/xdg-shell.xml",
  "thirdparty/viewporter.xml",
  "thirdparty/presentation-time.xml",
  "thirdparty/linux-dmabuf-v1.xml",
  "thirdparty/tablet-v2.xml",
  "thirdparty/linux-drm-syncobj-v1.xml",
};
const OUT_PATH = "src/wayland.zig";

const INPUT_SIZE_MAX     = 2 * 1024 * 1024;
const OUTPUT_BUFFER_SIZE = 64 * 1024;
// WL_CLOSURE_MAX_ARGS in libwayland
const ARGS_PER_MESSAGE_MAX = 20;
const NONE: u16            = std.math.maxInt(u16);
const LINE_LENGTH_MAX      = 110;

const HEADER =
  \\// This file is auto generated by src/gen_wayland.zig
  \\
  \\const std     = @import("std");
  \\pub const wire = @import("wayland_wire.zig");
  \\
  \\comptime {
  \\  std.debug.assert(@intFromEnum(Interface.wl_display) == wire.DISPLAY_INTERFACE);
  \\}
  \\
  \\// Layouts defined only in the text of protocol descriptions.
  \\
  \\/// Entry of the `zwp_linux_dmabuf_feedback_v1.format_table` file.
  \\pub const DmabufFormatTableEntry = extern struct {
  \\  format: u32,
  \\  _padding: u32,
  \\  modifier: u64,
  \\};
  \\
  \\/// Element of the `zwp_linux_dmabuf_feedback_v1.tranche_formats` array: index into the format table.
  \\pub const DmabufFormatIndex = u16;
  \\
  \\/// Content of the `zwp_linux_dmabuf_feedback_v1.main_device` and `tranche_target_device` arrays.
  \\pub const DeviceNumber = u64;
  \\
  \\comptime {
  \\  std.debug.assert(@sizeOf(DmabufFormatTableEntry) == 16);
  \\}
  \\
  \\/// `dev_t` from device major and minor numbers, like `makedev` of glibc.
  \\pub fn device_number(major: u32, minor: u32) DeviceNumber {
  \\  const ma: u64 = major;
  \\  const mi: u64 = minor;
  \\  return (ma & 0xfffff000) << 32 | (ma & 0xfff) << 8 | (mi & 0xffffff00) << 12 | (mi & 0xff);
  \\}
  \\
  \\fn object_new(conn: *wire.Connection, comptime T: type) wire.Error!T.Id {
  \\  return @enumFromInt(try conn.object_new(@intFromEnum(T.INTERFACE)));
  \\}
  \\
  \\fn object_new_server(conn: *wire.Connection, id: u32, comptime T: type) wire.Error!T.Id {
  \\  return @enumFromInt(try conn.object_new_server(id, @intFromEnum(T.INTERFACE)));
  \\}
  \\
;

const Range = struct {
  first: u16,
  count: u16 = 0,
};

const ArgType     = enum { int, uint, fixed, string, object, new_id, array, fd };
const MessageKind = enum { request, event };

const Protocol = struct {
  name: []const u8,
  interfaces: Range,
};

const Interface = struct {
  name: []const u8,
  summary: []const u8 = "",
  version: u32,
  messages: Range,
  enums: Range,
};

const Message = struct {
  name: []const u8,
  summary: []const u8 = "",
  kind: MessageKind,
  destructor: bool,
  args: Range,
};

const Arg = struct {
  name: []const u8,
  type: ArgType,
  interface_name: []const u8,
  enum_name: []const u8,
  allow_null: bool,
  interface_index: u16 = NONE,
  enum_index: u16 = NONE,
};

const Enum = struct {
  name: []const u8,
  bitfield: bool,
  interface_index: u16,
  entries: Range,
};

const Entry = struct {
  name: []const u8,
  summary: []const u8,
  value: u32,
};

fn Array(comptime T: type, comptime capacity: u16) type {
  comptime assert(capacity < NONE);
  return struct {
    items: [capacity]T = undefined,
    count: u16 = 0,

    fn append(array: *@This(), item: T) !void {
      if (capacity <= array.count) return error.CapacityExceeded;
      array.items[array.count] = item;
      array.count += 1;
    }

    fn last(array: *@This()) !*T {
      if (array.count == 0) return error.InvalidXml;
      return &array.items[array.count - 1];
    }

    fn slice(array: anytype, range: Range) @TypeOf(array.items[0..array.count]) {
      assert(range.first <= array.count);
      assert(range.count <= array.count - range.first);
      return array.items[range.first..][0..range.count];
    }
  };
}

const Database = struct {
  protocols: Array(Protocol, 16) = .{},
  interfaces: Array(Interface, 128) = .{},
  messages: Array(Message, 512) = .{},
  args: Array(Arg, 1024) = .{},
  enums: Array(Enum, 128) = .{},
  entries: Array(Entry, 1024) = .{},
};

var xml_buffer: [INPUT_SIZE_MAX]u8        = undefined;
var output_buffer: [OUTPUT_BUFFER_SIZE]u8 = undefined;
var database: Database                    = .{};

pub fn main() !void {
  var xml_len: usize = 0;
  for (IN_PATHS) |path| {
    const xml = try file_read(path, xml_buffer[xml_len..]);
    xml_len += xml.len;
    database_parse(&database, xml) catch |e| {
      log.err(@src(), "failed to parse {s}: {t}", .{ path, e });
      return e;
    };
  }
  try database_resolve(&database);

  const fd = try os.open(OUT_PATH, .{ .ACCMODE = .WRONLY, .CREAT = true, .TRUNC = true }, 0o644);
  defer os.close(fd);
  var output: log.Output = .init(fd, &output_buffer);
  try write_bindings(&output.writer, &database);
  try output.writer.flush();
}

fn file_read(path: [*:0]const u8, buffer: []u8) ![]const u8 {
  const fd = try os.open(path, .{}, 0);
  defer os.close(fd);

  var len: usize = 0;
  while (len < buffer.len) {
    const n = try os.read(fd, buffer[len..]);
    if (n == 0) return buffer[0..len];
    len += n;
  }
  return error.InputTooLarge;
}

const Attributes = struct {
  name: []const u8 = "",
  summary: []const u8 = "",
  version: []const u8 = "",
  type: []const u8 = "",
  interface: []const u8 = "",
  allow_null: []const u8 = "",
  @"enum": []const u8 = "",
  bitfield: []const u8 = "",
  value: []const u8 = "",
  contained: bool = false,
};

fn attributes_parse(parser: *XmlParser) !Attributes {
  var attributes: Attributes = .{};
  while (parser.next()) |token| {
    switch (token) {
      .attribute => |attribute| {
        inline for (@typeInfo(Attributes).@"struct".fields) |field| {
          if (field.type != []const u8) continue;
          const xml_name = comptime blk: {
            var name: [field.name.len]u8 = field.name[0..].*;
            std.mem.replaceScalar(u8, &name, '_', '-');
            const result = name;
            break :blk &result;
          };
          if (std.mem.eql(u8, attribute.name, xml_name)) @field(attributes, field.name) = attribute.value;
        }
      },
      .attribute_list_end => return attributes,
      .attribute_list_end_contained => {
        attributes.contained = true;
        return attributes;
      },
      else => return error.InvalidXml,
    }
  }
  return error.InvalidXml;
}

// Element whose children are being parsed.
const Owner = enum { none, protocol, interface, message, @"enum", entry, arg };

fn owner_parent(owner: Owner) !Owner {
  return switch (owner) {
    .none              => error.InvalidXml,
    .protocol          => .none,
    .interface         => .protocol,
    .message, .@"enum" => .interface,
    .entry             => .@"enum",
    .arg               => .message,
  };
}

fn database_parse(db: *Database, xml: []const u8) !void {
  var parser: XmlParser = .init(xml);
  var owner: Owner      = .none;
  while (parser.next()) |token| {
    switch (token) {
      .element_start => |element| {
        if (std.mem.eql(u8, element, "copyright")) {
          parser.skip_to_specific_element_end("copyright");
          continue;
        }
        const attributes = try attributes_parse(&parser);
        if (std.mem.eql(u8, element, "description")) {
          try database_parse_description(db, owner, attributes.summary);
          if (!attributes.contained) parser.skip_to_specific_element_end("description");
          continue;
        }
        const element_owner = try database_parse_element(db, element, &attributes);
        if (!attributes.contained) owner = element_owner;
      },
      .element_end => owner = try owner_parent(owner),
      .text => {},
      else => return error.InvalidXml,
    }
  }
  if (owner != .none) return error.InvalidXml;
}

fn database_parse_description(db: *Database, owner: Owner, summary: []const u8) !void {
  switch (owner) {
    .interface => (try db.interfaces.last()).summary = summary,
    .message => (try db.messages.last()).summary = summary,
    .entry => {
      const entry = try db.entries.last();
      if (entry.summary.len == 0) entry.summary = summary;
    },
    .none, .protocol, .@"enum", .arg => {},
  }
}

fn database_parse_element(db: *Database, element: []const u8, attributes: *const Attributes) !Owner {
  if (attributes.name.len == 0) return error.InvalidXml;

  if (std.mem.eql(u8, element, "protocol")) {
    try db.protocols.append(.{ .name = attributes.name, .interfaces = .{ .first = db.interfaces.count } });
    return .protocol;
  }
  if (std.mem.eql(u8, element, "interface")) {
    const protocol = try db.protocols.last();
    try db.interfaces.append(.{
      .name     = attributes.name,
      .version  = try std.fmt.parseInt(u32, attributes.version, 10),
      .messages = .{ .first = db.messages.count },
      .enums    = .{ .first = db.enums.count },
    });
    protocol.interfaces.count += 1;
    return .interface;
  }
  if (std.mem.eql(u8, element, "request") or std.mem.eql(u8, element, "event")) {
    const interface = try db.interfaces.last();
    try db.messages.append(.{
      .name       = attributes.name,
      .kind       = if (std.mem.eql(u8, element, "request")) .request else .event,
      .destructor = std.mem.eql(u8, attributes.type, "destructor"),
      .args       = .{ .first = db.args.count },
    });
    interface.messages.count += 1;
    return .message;
  }
  if (std.mem.eql(u8, element, "enum")) {
    const interface = try db.interfaces.last();
    try db.enums.append(.{
      .name            = attributes.name,
      .bitfield        = std.mem.eql(u8, attributes.bitfield, "true"),
      .interface_index = db.interfaces.count - 1,
      .entries         = .{ .first = db.entries.count },
    });
    interface.enums.count += 1;
    return .@"enum";
  }
  if (std.mem.eql(u8, element, "entry")) {
    const @"enum" = try db.enums.last();
    try db.entries.append(.{
      .name    = attributes.name,
      .summary = attributes.summary,
      .value   = try std.fmt.parseInt(u32, attributes.value, 0),
    });
    @"enum".entries.count += 1;
    return .entry;
  }
  if (std.mem.eql(u8, element, "arg")) {
    const message = try db.messages.last();
    if (ARGS_PER_MESSAGE_MAX <= message.args.count) return error.TooManyArgs;
    try db.args.append(.{
      .name           = attributes.name,
      .type           = std.meta.stringToEnum(ArgType, attributes.type) orelse return error.InvalidXml,
      .interface_name = attributes.interface,
      .enum_name      = attributes.@"enum",
      .allow_null     = std.mem.eql(u8, attributes.allow_null, "true"),
    });
    message.args.count += 1;
    return .arg;
  }
  log.err(@src(), "unknown element: {s}", .{ element });
  return error.InvalidXml;
}

fn interface_find(db: *const Database, name: []const u8) ?u16 {
  for (db.interfaces.items[0..db.interfaces.count], 0..) |*interface, i|
    if (std.mem.eql(u8, interface.name, name)) return @intCast(i);
  return null;
}

// `name` is either `interface.enum` or `enum` of the `interface_index` interface.
fn enum_find(db: *const Database, interface_index: u16, name: []const u8) ?u16 {
  var owner_index = interface_index;
  var enum_name   = name;
  if (std.mem.indexOfScalar(u8, name, '.')) |dot| {
    owner_index = interface_find(db, name[0..dot]) orelse return null;
    enum_name = name[dot + 1 ..];
  }
  const owner = &db.interfaces.items[owner_index];
  for (db.enums.slice(owner.enums), owner.enums.first..) |*@"enum", i|
    if (std.mem.eql(u8, @"enum".name, enum_name)) return @intCast(i);
  return null;
}

fn database_resolve(db: *Database) !void {
  if (db.interfaces.count == 0) return error.NoInterfaces;
  if (!std.mem.eql(u8, db.interfaces.items[0].name, "wl_display")) return error.FirstInterfaceNotDisplay;

  for (db.interfaces.items[0..db.interfaces.count], 0..) |*interface, interface_index| {
    for (db.messages.slice(interface.messages)) |*message| {
      var new_ids: u32 = 0;
      for (db.args.slice(message.args)) |*arg| {
        if (arg.interface_name.len != 0) {
          arg.interface_index = interface_find(db, arg.interface_name) orelse {
            log.err(@src(), "{s}.{s}: unknown interface {s}", .{
              interface.name,
              message.name,
              arg.interface_name,
            });
            return error.UnknownInterface;
          };
        }
        if (arg.enum_name.len != 0) {
          arg.enum_index = enum_find(db, @intCast(interface_index), arg.enum_name) orelse {
            log.err(@src(), "{s}.{s}: unknown enum {s}", .{ interface.name, message.name, arg.enum_name });
            return error.UnknownEnum;
          };
        }
        if (arg.type == .new_id) new_ids += 1;
        if (arg.type == .new_id and message.kind == .event and arg.interface_index == NONE) {
          log.err(@src(), "{s}.{s}: event with untyped new_id", .{ interface.name, message.name });
          return error.UntypedNewIdEvent;
        }
      }
      if (1 < new_ids) {
        log.err(@src(), "{s}.{s}: more than one new_id", .{ interface.name, message.name });
        return error.MultipleNewIds;
      }
    }
  }
}

const TitleCase = struct {
  name: []const u8,

  pub fn format(title_case: TitleCase, w: *Writer) Writer.Error!void {
    var upper = true;
    for (title_case.name) |c| {
      if (c == '_') {
        upper = true;
        continue;
      }
      try w.writeByte(if (upper) std.ascii.toUpper(c) else c);
      upper = false;
    }
  }
};

fn id(name: []const u8) std.zig.FormatId {
  return std.zig.fmtId(name);
}

// Word wraps `summary` into doc comment lines.
fn write_summary(w: *Writer, indent: []const u8, summary: []const u8) !void {
  if (summary.len == 0) return;
  var line_len: usize = 0;
  var words           = std.mem.tokenizeAny(u8, summary, &std.ascii.whitespace);
  while (words.next()) |word| {
    if (line_len != 0 and LINE_LENGTH_MAX < line_len + 1 + word.len) {
      try w.writeAll("\n");
      line_len = 0;
    }
    if (line_len == 0) {
      try w.print("{s}///", .{ indent });
      line_len = indent.len + 3;
    }
    try w.print(" {s}", .{ word });
    line_len += 1 + word.len;
  }
  try w.writeAll("\n");
}

fn write_enum_type(w: *Writer, db: *const Database, enum_index: u16) !void {
  const @"enum" = &db.enums.items[enum_index];
  const owner   = &db.interfaces.items[@"enum".interface_index];
  try w.print("{s}.{f}", .{ owner.name, TitleCase{ .name = @"enum".name } });
}

fn write_arg_type(w: *Writer, db: *const Database, arg: *const Arg) !void {
  if (arg.enum_index != NONE) return write_enum_type(w, db, arg.enum_index);
  switch (arg.type) {
    .int => try w.writeAll("i32"),
    .uint => try w.writeAll("u32"),
    .fixed => try w.writeAll("wire.Fixed"),
    .string => try w.writeAll(if (arg.allow_null) "?[]const u8" else "[]const u8"),
    .array => try w.writeAll("[]const u8"),
    .fd => try w.writeAll("std.os.linux.fd_t"),
    .object, .new_id => {
      if (arg.interface_index == NONE) return w.writeAll("u32");
      try w.print("{s}.Id", .{ db.interfaces.items[arg.interface_index].name });
    },
  }
}

fn write_bindings(w: *Writer, db: *const Database) !void {
  try w.writeAll(HEADER);

  try w.writeAll("\npub const Interface = enum(u8) {\n  none,\n");
  for (db.interfaces.items[0..db.interfaces.count]) |*interface|
    try w.print("  {s},\n", .{ interface.name });
  try w.writeAll("};\n");

  for (db.protocols.items[0..db.protocols.count]) |*protocol| {
    try w.print("\n// Protocol: {s}\n", .{ protocol.name });
    for (protocol.interfaces.first..protocol.interfaces.first + protocol.interfaces.count) |i|
      try write_interface(w, db, @intCast(i));
  }

  try write_events(w, db);
}

fn write_interface(w: *Writer, db: *const Database, interface_index: u16) !void {
  const interface = &db.interfaces.items[interface_index];
  try w.writeAll("\n");
  try write_summary(w, "", interface.summary);
  try w.print(
    \\pub const {[name]s} = struct {{
    \\  pub const NAME                 = "{[name]s}";
    \\  pub const VERSION              = {[version]d};
    \\  pub const INTERFACE: Interface = .{[name]s};
    \\  pub const Id                   = enum(u32) {{ none = 0, _ }};
    \\
  , .{ .name = interface.name, .version = interface.version });

  for (interface.enums.first..interface.enums.first + interface.enums.count) |i| {
    const @"enum" = &db.enums.items[i];
    if (@"enum".bitfield)
      try write_bitfield(w, db, @"enum")
    else
      try write_enum(w, db, @"enum");
  }

  var requests_count: u16 = 0;
  var events_count: u16   = 0;
  for (db.messages.slice(interface.messages)) |*message| {
    switch (message.kind) {
      .request => {
        try write_request(w, db, message, requests_count);
        requests_count += 1;
      },
      .event => events_count += 1,
    }
  }
  if (0 < events_count) try write_interface_events(w, db, interface);
  try w.writeAll("};\n");
}

fn write_enum(w: *Writer, db: *const Database, @"enum": *const Enum) !void {
  try w.print("\n  pub const {f} = enum(u32) {{\n", .{ TitleCase{ .name = @"enum".name } });
  for (db.entries.slice(@"enum".entries)) |*entry| {
    try write_summary(w, "    ", entry.summary);
    try w.print("    {f} = {d},\n", .{ id(entry.name), entry.value });
  }
  try w.writeAll("    _,\n  };\n");
}

// First entry with only the `bit` set.
fn write_bitfield_entry(entries: []const Entry, bit: u32) ?*const Entry {
  for (entries) |*entry|
    if (entry.value == @as(u32, 1) << @intCast(bit)) return entry;
  return null;
}

fn write_bitfield(w: *Writer, db: *const Database, @"enum": *const Enum) !void {
  const entries = db.entries.slice(@"enum".entries);
  try w.print("\n  pub const {f} = packed struct(u32) {{\n", .{ TitleCase{ .name = @"enum".name } });

  var bit_next: u32 = 0;
  for (0..32) |bit| {
    const entry = write_bitfield_entry(entries, @intCast(bit)) orelse continue;
    if (bit_next < bit) try w.print("    _{d}: u{d} = 0,\n", .{ bit_next, bit - bit_next });
    try write_summary(w, "    ", entry.summary);
    try w.print("    {f}: bool = false,\n", .{ id(entry.name) });
    bit_next = @intCast(bit + 1);
  }
  if (bit_next < 32) try w.print("    _{d}: u{d} = 0,\n", .{ bit_next, 32 - bit_next });

  for (entries) |*entry| {
    if (entry.value == 0) {
      try write_summary(w, "    ", entry.summary);
      try w.print("    pub const {f}: @This() = .{{}};\n", .{ id(entry.name) });
      continue;
    }
    // Combined or duplicate bits are constants.
    const single_bit = entry.value & (entry.value - 1) == 0;
    if (single_bit and write_bitfield_entry(entries, @ctz(entry.value)) == entry) continue;
    try write_summary(w, "    ", entry.summary);
    try w.print("    pub const {f}: @This() = @bitCast(@as(u32, {d}));\n", .{ id(entry.name), entry.value });
  }
  try w.writeAll("  };\n");
}

// Expression converting argument `name` to u32.
fn write_request_uint(w: *Writer, db: *const Database, arg: *const Arg) !void {
  if (arg.enum_index != NONE) {
    if (db.enums.items[arg.enum_index].bitfield)
      return w.print("@bitCast({f})", .{ id(arg.name) });
    return w.print("@intFromEnum({f})", .{ id(arg.name) });
  }
  switch (arg.type) {
    .int => try w.print("@bitCast({f})", .{ id(arg.name) }),
    .uint => try w.print("{f}", .{ id(arg.name) }),
    .fixed => try w.print("@bitCast(@intFromEnum({f}))", .{ id(arg.name) }),
    .new_id => try w.print("@intFromEnum({f})", .{ id(arg.name) }),
    .object => {
      if (arg.interface_index == NONE) return w.print("{f}", .{ id(arg.name) });
      try w.print("@intFromEnum({f})", .{ id(arg.name) });
    },
    .string, .array, .fd => unreachable,
  }
}

fn write_request_signature(w: *Writer, db: *const Database, message: *const Message, multiline: bool) !void {
  const separator = if (multiline) ",\n    " else ", ";
  try w.print("  pub fn {f}({s}conn: *wire.Connection{s}self: Id", .{
    id(message.name),
    if (multiline) "\n    " else "",
    separator,
  });
  var new_id: ?*const Arg = null;
  for (db.args.slice(message.args)) |*arg| {
    if (arg.type == .new_id) {
      new_id = arg;
      if (arg.interface_index == NONE)
        try w.print("{s}comptime T: type{s}version: u32", .{ separator, separator });
      continue;
    }
    try w.print("{s}{f}: ", .{ separator, id(arg.name) });
    try write_arg_type(w, db, arg);
  }
  try w.writeAll(if (multiline) ",\n  ) wire.Error!" else ") wire.Error!");
  if (new_id) |arg| {
    if (arg.interface_index == NONE)
      try w.writeAll("T.Id")
    else
      try write_arg_type(w, db, arg);
  } else {
    try w.writeAll("void");
  }
  try w.writeAll(" {\n");
}

fn write_request(w: *Writer, db: *const Database, message: *const Message, opcode: u16) !void {
  const args = db.args.slice(message.args);

  try w.writeAll("\n");
  try write_summary(w, "  ", message.summary);
  var line_buffer: [LINE_LENGTH_MAX + 1]u8 = undefined;
  var line: Writer                         = .fixed(&line_buffer);
  if (write_request_signature(&line, db, message, false)) {
    try w.writeAll(line.buffered());
  } else |_| {
    try write_request_signature(w, db, message, true);
  }

  var new_id: ?*const Arg = null;
  for (args) |*arg| {
    if (arg.type == .new_id) new_id = arg;
  }

  if (new_id) |arg| {
    const name = if (arg.interface_index == NONE) "T" else db.interfaces.items[arg.interface_index].name;
    try w.print("    const {f} = try object_new(conn, {s});\n", .{ id(arg.name), name });
  }

  var size: u32 = 8;
  var fds: u32  = 0;
  for (args) |*arg| {
    switch (arg.type) {
      .int, .uint, .fixed, .object => size += 4,
      .new_id                      => size += if (arg.interface_index == NONE) 8 else 4,
      .fd                          => fds += 1,
      .string, .array              => {},
    }
  }
  try w.print("    const message_size  = {d}", .{ size });
  for (args) |*arg| {
    switch (arg.type) {
      .string => try w.print(" + wire.string_size({f})", .{ id(arg.name) }),
      .array  => try w.print(" + wire.array_size({f})", .{ id(arg.name) }),
      .new_id => if (arg.interface_index == NONE) try w.writeAll(" + wire.string_size(T.NAME)"),
      else    => {},
    }
  }
  try w.print(
    ";\n    const message_start = try conn.message_begin(@intFromEnum(self), {d}, message_size, {d});\n",
    .{ opcode, fds },
  );

  for (args) |*arg| {
    switch (arg.type) {
      .string => try w.print("    conn.put_string({f});\n", .{ id(arg.name) }),
      .array => try w.print("    conn.put_array({f});\n", .{ id(arg.name) }),
      .fd => try w.print("    conn.put_fd({f});\n", .{ id(arg.name) }),
      else => {
        if (arg.type == .new_id and arg.interface_index == NONE)
          try w.writeAll("    conn.put_string(T.NAME);\n    conn.put_uint(version);\n");
        try w.writeAll("    conn.put_uint(");
        try write_request_uint(w, db, arg);
        try w.writeAll(");\n");
      },
    }
  }
  try w.writeAll("    conn.message_end(message_start);\n");
  if (message.destructor) try w.writeAll("    conn.object_destroy(@intFromEnum(self));\n");
  if (new_id) |arg| try w.print("    return {f};\n", .{ id(arg.name) });
  try w.writeAll("  }\n");
}

// Expression decoding `arg` from `reader`.
fn write_event_decode_arg(w: *Writer, db: *const Database, arg: *const Arg) !void {
  if (arg.enum_index != NONE) {
    if (db.enums.items[arg.enum_index].bitfield)
      return w.writeAll("@bitCast(try reader.uint())");
    return w.writeAll("@enumFromInt(try reader.uint())");
  }
  switch (arg.type) {
    .int => try w.writeAll("@bitCast(try reader.uint())"),
    .uint => try w.writeAll("try reader.uint()"),
    .fixed => try w.writeAll("@enumFromInt(@as(i32, @bitCast(try reader.uint())))"),
    .string => try w.writeAll(if (arg.allow_null) "try reader.string_optional()" else "try reader.string()"),
    .array => try w.writeAll("try reader.array()"),
    .fd => try w.writeAll("try conn.fd_take()"),
    .object => {
      if (arg.interface_index == NONE) return w.writeAll("try reader.uint()");
      try w.writeAll("@enumFromInt(try reader.uint())");
    },
    .new_id => try w.print(
      "try object_new_server(conn, try reader.uint(), {s})",
      .{ db.interfaces.items[arg.interface_index].name },
    ),
  }
}

fn write_interface_events(w: *Writer, db: *const Database, interface: *const Interface) !void {
  const messages = db.messages.slice(interface.messages);

  try w.writeAll("\n  pub const EventOpcode = enum(u16) {\n");
  var opcode: u16 = 0;
  for (messages) |*message| {
    if (message.kind != .event) continue;
    try w.print("    {f} = {d},\n", .{ id(message.name), opcode });
    opcode += 1;
  }
  try w.writeAll("  };\n\n  pub const Event = union(EventOpcode) {\n");
  for (messages) |*message| {
    if (message.kind != .event) continue;
    try w.print("    {f}: Event.{f},\n", .{ id(message.name), TitleCase{ .name = message.name } });
  }
  for (messages) |*message| {
    if (message.kind != .event) continue;
    try w.writeAll("\n");
    try write_summary(w, "    ", message.summary);
    try w.print("    pub const {f} = struct {{\n", .{ TitleCase{ .name = message.name } });
    for (db.args.slice(message.args)) |*arg| {
      try w.print("      {f}: ", .{ id(arg.name) });
      try write_arg_type(w, db, arg);
      try w.writeAll(",\n");
    }
    try w.writeAll("    };\n");
  }
  try w.writeAll("  };\n");

  var uses_conn   = false;
  var uses_reader = false;
  for (messages) |*message| {
    if (message.kind != .event) continue;
    for (db.args.slice(message.args)) |*arg| {
      if (arg.type == .fd or arg.type == .new_id) uses_conn = true;
      if (arg.type != .fd) uses_reader = true;
    }
  }
  try w.writeAll(
    \\
    \\  pub fn event_decode(conn: *wire.Connection, opcode: u16, payload: []const u32) wire.Error!Event {
    \\
  );
  if (!uses_conn) try w.writeAll("    _ = conn;\n");
  if (uses_reader)
    try w.writeAll("    var reader: wire.Reader = .{ .payload = payload };\n")
  else
    try w.writeAll("    _ = payload;\n");
  try w.writeAll("    switch (opcode) {\n");
  opcode = 0;
  for (messages) |*message| {
    if (message.kind != .event) continue;
    try w.print("      {d} => return .{{ .{f} = .{{\n", .{ opcode, id(message.name) });
    for (db.args.slice(message.args)) |*arg| {
      try w.print("        .{f} = ", .{ id(arg.name) });
      try write_event_decode_arg(w, db, arg);
      try w.writeAll(",\n");
    }
    try w.writeAll("      } },\n");
    opcode += 1;
  }
  try w.writeAll("      else => return error.InvalidMessage,\n    }\n  }\n");
}

fn interface_has_events(db: *const Database, interface: *const Interface) bool {
  for (db.messages.slice(interface.messages)) |*message|
    if (message.kind == .event) return true;
  return false;
}

fn write_events(w: *Writer, db: *const Database) !void {
  const interfaces = db.interfaces.items[0..db.interfaces.count];

  try w.writeAll(
    \\
    \\pub const Message = struct {
    \\  id: u32,
    \\  event: Event,
    \\
    \\  pub const Event = union(enum) {
    \\
  );
  for (interfaces) |*interface| {
    if (!interface_has_events(db, interface)) continue;
    try w.print("    {s}: {s}.Event,\n", .{ interface.name, interface.name });
  }
  try w.writeAll(
    \\  };
    \\};
    \\
    \\/// Decodes the next complete received message. Messages for unknown objects are skipped.
    \\pub fn event_next(conn: *wire.Connection) wire.Error!?Message {
    \\  for (0..wire.RECV_MESSAGES_MAX) |_| {
    \\    const message              = try conn.message_next() orelse return null;
    \\    const interface: Interface = @enumFromInt(conn.object_interface(message.id));
    \\    switch (interface) {
    \\      .wl_display => {
    \\        const event = try wl_display.event_decode(conn, message.opcode, message.payload);
    \\        if (event == .delete_id) conn.object_free(event.delete_id.id);
    \\        return .{ .id = message.id, .event = .{ .wl_display = event } };
    \\      },
    \\
  );
  for (interfaces[1..]) |*interface| {
    if (!interface_has_events(db, interface)) continue;
    try w.print(
      \\      .{[name]s} => {{
      \\        const event = try {[name]s}.event_decode(conn, message.opcode, message.payload);
      \\        return .{{ .id = message.id, .event = .{{ .{[name]s} = event }} }};
      \\      }},
      \\
    , .{ .name = interface.name });
  }
  try w.writeAll("      .none,\n");
  for (interfaces) |*interface| {
    if (interface_has_events(db, interface)) continue;
    try w.print("      .{s},\n", .{ interface.name });
  }
  try w.writeAll(
    \\      => {},
    \\    }
    \\  }
    \\  return null;
    \\}
    \\
  );
}

fn test_database(xml: []const u8) !*Database {
  const db = struct {
    var db: Database = .{};
  };
  db.db = .{};
  try database_parse(&db.db, xml);
  try database_resolve(&db.db);
  return &db.db;
}

const TEST_XML =
  \\<?xml version="1.0" encoding="UTF-8"?>
  \\<protocol name="test">
  \\  <copyright>
  \\    text
  \\  </copyright>
  \\  <interface name="wl_display" version="1">
  \\    <description summary="core
  \\      object">
  \\      Long description.
  \\    </description>
  \\    <request name="bind">
  \\      <description summary="bind"/>
  \\      <arg name="name" type="uint"/>
  \\      <arg name="id" type="new_id"/>
  \\    </request>
  \\    <event name="title">
  \\      <arg name="title" type="string" allow-null="true" summary="title"/>
  \\      <arg name="transform" type="int" enum="wl_output.transform"/>
  \\    </event>
  \\    <enum name="caps" bitfield="true">
  \\      <entry name="none" value="0"/>
  \\      <entry name="a" value="1"/>
  \\      <entry name="c" value="0x8" summary="c"/>
  \\      <entry name="ac" value="9"/>
  \\    </enum>
  \\  </interface>
  \\  <interface name="wl_output" version="4">
  \\    <request name="release" type="destructor"/>
  \\    <enum name="transform">
  \\      <entry name="normal" value="0"/>
  \\      <entry name="90" value="1"/>
  \\    </enum>
  \\  </interface>
  \\</protocol>
;

test "parse" {
  const db = try test_database(TEST_XML);
  try std.testing.expectEqual(1, db.protocols.count);
  try std.testing.expectEqual(2, db.interfaces.count);
  try std.testing.expectEqual(3, db.messages.count);
  try std.testing.expectEqual(4, db.args.count);
  try std.testing.expectEqual(2, db.enums.count);
  try std.testing.expectEqual(6, db.entries.count);

  const display = &db.interfaces.items[0];
  try std.testing.expectEqualStrings("core\n      object", display.summary);
  try std.testing.expectEqualStrings("bind", db.messages.items[0].summary);
  try std.testing.expect(db.messages.items[2].destructor);

  const title = &db.args.items[2];
  try std.testing.expect(title.allow_null);
  try std.testing.expectEqual(.string, title.type);
  const transform = &db.args.items[3];
  try std.testing.expectEqual(1, transform.enum_index);
  try std.testing.expectEqual(NONE, db.args.items[1].interface_index);
  try std.testing.expectEqual(8, db.entries.items[2].value);
}

test "parse errors" {
  try std.testing.expectError(error.UnknownInterface, test_database(
    \\<protocol name="p"><interface name="wl_display" version="1">
    \\<request name="r"><arg name="a" type="object" interface="nope"/></request>
    \\</interface></protocol>
  ));
  try std.testing.expectError(error.UnknownEnum, test_database(
    \\<protocol name="p"><interface name="wl_display" version="1">
    \\<request name="r"><arg name="a" type="uint" enum="nope"/></request>
    \\</interface></protocol>
  ));
  try std.testing.expectError(error.FirstInterfaceNotDisplay, test_database(
    \\<protocol name="p"><interface name="wl_output" version="1"/></protocol>
  ));
}

test "write" {
  const db                  = try test_database(TEST_XML);
  var buffer: [16 * 1024]u8 = undefined;
  var w: Writer             = .fixed(&buffer);
  try write_bindings(&w, db);
  const output = w.buffered();

  const expected = [_][]const u8{
    "/// core object\npub const wl_display = struct {",
    "pub fn bind(conn: *wire.Connection, self: Id, name: u32, comptime T: type, version: u32) " ++
      "wire.Error!T.Id {",
    "const message_size  = 20 + wire.string_size(T.NAME);",
    "title: ?[]const u8,\n      transform: wl_output.Transform,",
    ".transform = @enumFromInt(try reader.uint()),",
    "a: bool = false,\n    _1: u2 = 0,\n    /// c\n    c: bool = false,\n    _4: u28 = 0,",
    "pub const none: @This() = .{};",
    "pub const ac: @This() = @bitCast(@as(u32, 9));",
    "@\"90\" = 1,",
    "conn.object_destroy(@intFromEnum(self));",
    "conn.put_uint(version);\n    conn.put_uint(@intFromEnum(id));",
    ".none,\n      .wl_output,\n      => {},",
  };
  for (expected) |e| {
    if (std.mem.indexOf(u8, output, e) == null) {
      std.debug.print("missing:\n{s}\n", .{ e });
      return error.TestUnexpectedResult;
    }
  }
}
